### ISSUE TITLE
Metadata Export

### ISSUE THREAD

**Issue by edocnikufesin** [AnastasiiaPirus/source-code-for-blogs#1]
/app/layout.tsx causing this compile error:

ReactServerComponentsError:

You are attempting to export "metadata" from a component marked with "use client", which is disallowed.

**Comment by AnastasiiaPirus** [comment]
Hi @edocnikufesin , 
Thank you for noticing!
I've fixed it in commit aa6e33469fb57143b5d396c8750a94370b2ee97e . The issue was adding 'use client' to layout.tsx. Solution is to move the useState hook to child component so we won't need 'use client' in 'layout'.
